-- MySQL Script generated by MySQL Workbench
-- 04/24/16 21:09:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticket
-- -----------------------------------------------------
-- 火车票数据库

-- -----------------------------------------------------
-- Schema ticket
--
-- 火车票数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket` DEFAULT CHARACTER SET utf8 ;
USE `ticket` ;

-- -----------------------------------------------------
-- Table `ticket`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`train` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `train_nick` VARCHAR(20) NOT NULL,
  `status` INT NOT NULL,
  `desc` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `train_nick_UNIQUE` (`train_nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`station` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `station_nick` VARCHAR(20) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `station_nick_UNIQUE` (`station_nick` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`seat` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `train_id` BIGINT(20) UNSIGNED NOT NULL,
  `carriage_num` INT UNSIGNED NOT NULL,
  `seat_num` INT UNSIGNED NOT NULL,
  `status` INT NOT NULL,
  `desc` VARCHAR(20) NULL,
  INDEX `PRIMARAY` (`id` ASC),
  UNIQUE INDEX `pos_uniq` (`carriage_num` ASC, `seat_num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `user_nick` VARCHAR(20) NOT NULL,
  `user_identity_card_id` VARCHAR(20) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_identity_card_id_UNIQUE` (`user_identity_card_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`order` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `gmt_create` DATETIME(14) NOT NULL,
  `gmt_modified` DATETIME(14) NOT NULL,
  `train_id` BIGINT(20) UNSIGNED NOT NULL,
  `train_name` VARCHAR(10) NOT NULL,
  `train_desc` VARCHAR(20) NOT NULL,
  `start_station_id` BIGINT(20) UNSIGNED NOT NULL,
  `start_station_nick` VARCHAR(20) NOT NULL,
  `end_station_id` BIGINT(20) UNSIGNED NOT NULL,
  `end_station_nick` VARCHAR(20) NOT NULL,
  `seat_id` BIGINT(20) UNSIGNED NOT NULL,
  `seat_name` VARCHAR(20) NOT NULL,
  `seat_desc` VARCHAR(20) NOT NULL,
  `depart_time` DATETIME(15) NOT NULL,
  `price` INT NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_nick` VARCHAR(20) NOT NULL,
  `user_identity_card_id` VARCHAR(20) NOT NULL,
  `status` INT NOT NULL,
  `order_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `train_id_idx` (`train_id` ASC),
  INDEX `start_station_id_idx` (`start_station_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `end_station_id_idx` (`end_station_id` ASC),
  INDEX `seat_id_idx` (`seat_id` ASC),
  CONSTRAINT `train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `ticket`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `start_station_id`
    FOREIGN KEY (`start_station_id`)
    REFERENCES `ticket`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `end_station_id`
    FOREIGN KEY (`end_station_id`)
    REFERENCES `ticket`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seat_id`
    FOREIGN KEY (`seat_id`)
    REFERENCES `ticket`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticket`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`train_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`train_instance` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `depart_time` DATETIME NOT NULL,
  `train_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `train_id_idx` (`train_id` ASC),
  CONSTRAINT `train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `ticket`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`seat_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`seat_instance` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `seat_id` BIGINT(20) UNSIGNED NOT NULL,
  `train_instance_id` BIGINT(20) UNSIGNED NOT NULL,
  `seq` INT UNSIGNED NOT NULL,
  `start_station_id` BIGINT(20) UNSIGNED NOT NULL,
  `end_station_id` BIGINT(20) UNSIGNED NOT NULL,
  `seq` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `seat_uniq` (`seat_id` ASC, `train_instance_id` ASC),
  UNIQUE INDEX `segment_uniq` (`train_instance_id` ASC, `start_station_id` ASC, `end_station_id` ASC),
  UNIQUE INDEX `seq_uniq` (`train_instance_id` ASC, `seq` ASC),
  INDEX `start_station_id_idx` (`start_station_id` ASC),
  INDEX `end_station_id_idx` (`end_station_id` ASC),
  CONSTRAINT `seat_id`
    FOREIGN KEY (`seat_id`)
    REFERENCES `ticket`.`seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `train_instance_id`
    FOREIGN KEY (`train_instance_id`)
    REFERENCES `ticket`.`train_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `start_station_id`
    FOREIGN KEY (`start_station_id`)
    REFERENCES `ticket`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `end_station_id`
    FOREIGN KEY (`end_station_id`)
    REFERENCES `ticket`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`station_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`station_instance` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `train_id` BIGINT(20) UNSIGNED NOT NULL,
  `seq` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq` (`train_id` ASC, `seq` ASC),
  CONSTRAINT `train_id`
    FOREIGN KEY (`train_id`)
    REFERENCES `ticket`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
